# Generated by Django 2.1.7 on 2019-04-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                #('portion', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('fathername', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=50)),
            ],
        ),
    ]
